server.port=8080
spring.application.name=crm-project-backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/crmdb
spring.datasource.username=postgres
spring.datasource.password=4152
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.schemas=public
spring.flyway.validate-on-migrate=true
spring.flyway.clean-disabled=true
